# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
es:
  languageCode: es
  contentDir: content/es
  title: El Proyecto CHERIsHED
  params:
    description: Estamos estudiando la exposición a químicos disruptores endocrinos en New Haven, Connecticut. Para este proyecto, estamos interesados en ver si distintas áreas o grupos demográficos dentro de New Haven tienen una exposición diferente a los disruptores endocrinos. También estamos interesados en entender cómo la exposición a los disruptores endocrinos influye en el desarrollo infantil. A los participantes en este estudio se les pedirá que recolecten muestras biológicas (como orina) de ellos mismos y de sus bebés y que recolecten algunas muestras de monitoreo ambiental en su casa (como agua del grifo). También se les solicitará a los participantes que llenen un cuestionario. Los riesgos para este estudio son mínimos. Las madres que participen recibirán un informe personalizado sobre su exposición y la de su bebé a los disruptores endocrinos. También recibirán $ 40 en compensación al completar su participación. Comuníquese con la investigadora, Carlye Chaney, en el siguiente correo electrónico Carlye.Chaney@yale.edu si cumple con los criterios del estudio y está interesada en participar o tiene alguna pregunta. Este estudio ha recibido la aprobación ética del Comité de Sujetos Humanos de Yale se...
  menu:
    main:
      - name: El Proyecto CHERIsHED
        url: '#about'
        weight: 1

